development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "00969f9a44758d49128989a978ec00bf25bd771e6f7bad7a0f37bf17ed1c2051"
  signature_expiration: 3600 # one hour
